apiVersion: v1
kind: Service
metadata:
  name: wordpress  
  labels:
    app: wordpress
spec:
  type: ClusterIP  
  ports:
    - port: 8080  
      targetPort: 8080  
  selector:
    app: wordpress  

